Added unit test cases
TaskarCenterAtUW/TDEI-python-osw-validation pull request #2
Opened 2023-10-11 19:48 UTC by sujata-m

This PR contains following changes - 

- Added actual validation instead of dummy, using `python-osw-validation` package
- Added Unit test cases
- Added integration tests
- Added test harness
- Added `test-case-enumeration.md`
- Updated `README.md` file

2023-10-12 07:57 UTC, susrisha requested changes

2023-10-12 07:57 UTC, susrisha commented on README.md
> +  - Added the `isValid` and `validationMessage` keys to the original message
Adds (instead of added)

2023-10-12 07:57 UTC, susrisha commented on README.md
> +`QUEUECONNECTION` is not being used in this application but this is the main requirement for `python-ms-core` package
`QUEUECONNECTION` is used to send out the messages and listen to messages.

2023-10-12 10:14 UTC, sureshgaussian requested changes
Also please add 'reports' folder to .gitignore file.

2023-10-13 08:52 UTC, sujata-m commented on README.md
> +Follow the steps to install the node packages required for both building and running the application
oops!

2023-10-13 10:28 UTC, susrisha approved these changes

2023-10-13 14:18 UTC, sureshgaussian approved these changes
Ran the code locally, tested unit tests and integration tests.

2023-10-16 05:39 UTC, merged